### ISSUE TITLE
Realtek most likely updated HDX_GenericExt_RTK.inf in 6.0.8692.1 because simply bumping date and version number results in an INF with invalid hash

### ISSUE THREAD

**Issue by pal1000** [pal1000/Realtek-UAD-generic#1]
Call @alanfox2000. Maybe he has an idea where I could find it. It must have these hashes according to `hdxrtext.cat`:
`8AFD51045DF2F45A100EB9D270F38518A4A6070CE2288AD98B0B806784B47379`
`D461EA3E34C562FFA5E21A6E347298B07F714598`
Output from my setup script:
````
HDAUDIO\FUNC_01&VEN_10EC&DEV_0282&SUBSYS_10280597&REV_1000\4&2AF4EA01&0&0001: Disabled
1 device(s) disabled.

No matching devices found.

HDAUDIO\FUNC_01&VEN_10EC&DEV_0282&SUBSYS_10280597&REV_1000\4&2AF4EA01&0&0001: Removed
1 device(s) were removed.

No devices were removed.

Microsoft PnP Utility

Driver package deleted successfully.

Microsoft PnP Utility

Driver package deleted successfully.

Microsoft PnP Utility

Driver package deleted successfully.

Microsoft PnP Utility

Driver package deleted successfully.


Done uninstalling driver

Press any key to continue . . .
Microsoft PnP Utility

Adding driver package:  Codec\HDXRT.inf
Driver package added successfully.
Published Name:         oem2.inf

Adding driver package:  Codec\HDX_GenericExt_RTK.inf
Failed to add driver package: The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.

Adding driver package:  RealtekAPO_682\RealtekAPO.inf
Driver package added successfully.
Published Name:         oem3.inf

Adding driver package:  RealtekHSA_177\RealtekHSA.inf
Driver package added successfully.
Published Name:         oem4.inf

Adding driver package:  RealtekService_164\RealtekService.inf
Driver package added successfully.
Published Name:         oem5.inf

Total driver packages:  5
Added driver packages:  4

Done installing driver

Press any key to continue . . .
````

**Comment by shibajee** [comment]
r u on any kind of forum/site where people discuss/troubleshoot ur release and keep touch with u regularly/periodically ?

**Comment by pal1000** [comment]
@shibajee, I am present on station-drivers.com with same handle. You can find me there too. I link my releases in `[DRIVERS] Realtek High Definition Audio Codecs (HDA/UAD)` forum thread for visibility. Github statistics indicate that latest release has 50+ downloads/day.

**Comment by pal1000** [comment]
I found a newer version of `HDX_GenericExt_RTK.inf ` in `ftp://spcust@ftp3.realtek.com/DCHU/TEMP/8671_UAD_test_v2.zip`. I think Realtek doesn't update this component often because it is not used by any OEM UAD driver unlike `HDXRT.inf` that is present in a few OEM UAD drivers consistently like Compal or MSI Nahimic to name a few.

Best way to find latest copy of `HDX_GenericExt_RTK.inf` is by performing a double search with an advanced FTP client on `ftp://spcust@ftp3.realtek.com/` and look for files with names containing `Universal_Audio_Driver` and `Test` for first search and `UAD_Test` for second search and finally pick the package that's newest in the combined results of the 2 searches.

This outcome seams good enough to close this issue for now.
