### ISSUE TITLE
Changelog for updates?

### ISSUE THREAD

**Issue by demberto** [pal1000/Realtek-UAD-generic#101]
Ik this isn't in your hands but I can't find a changelog for the updates elsewhere too. What is the reason updates are so frequent?

**Comment by pal1000** [comment]
It's because I keep pace with Realtek UAD OEM packages that are provided on various forums.

Change-logs may be found now and then on the official websites of some OEMs which provide the  Realtek UAD driver of interest.

**Comment by demberto** [comment]
Do you have some links? Shame on Realtek, they should be doing this

**Comment by epman100** [comment]
> Do you have some links? Shame on Realtek, they should be doing this

yea right
like how exactly should Realtek do this when they don't even update their audio drivers on their own web site?
