### ISSUE TITLE
Startup script not existed?

### ISSUE THREAD

**Issue by atipaHy** [pal1000/Realtek-UAD-generic#106]
I installed the package a couple of months ago. Since an update I am keeping to get this cmd window all the time. Anyone has an idea how to locate it and remove it?
![123](https://user-images.githubusercontent.com/14053102/167298981-29546103-ab4a-4c19-8a88-21560c6373d1.png)

**Comment by pal1000** [comment]
In an elevated command prompt do
`REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /t REG_SZ /v Shell /d "explorer.exe" /f`

**Comment by atipaHy** [comment]
Thanks for fast response.
