### ISSUE TITLE
Setup Crashes when Opened.

### ISSUE THREAD

**Issue by bluesnipersguy** [pal1000/Realtek-UAD-generic#108]
I just need some help here.

**Comment by pal1000** [comment]
You may have a problems with Powershell as that's what is used to request admin rights.
Does UAC prompt show up?

**Comment by bluesnipersguy** [comment]
yes.

**Comment by bluesnipersguy** [comment]
wait hold on when i open it?

**Comment by bluesnipersguy** [comment]
fixed it
