### ISSUE TITLE
Issue on the EVOC P775TM1-R: When I plug in a headset to the 3.5mm amplified headset jack, I hear audio on both the headset and onboard speakers.

### ISSUE THREAD

**Issue by Brainiarc7** [pal1000/Realtek-UAD-generic#11]
Hello there,

My issue is as described above.
The system is an [EVOC P775TM1-R](https://www.hidevolution.com/evoc-high-performance-systems-p775tm-r-17-3-fhd-144hz-qhd-120hz-qfhd-60hz-i5-9600k-i7-9700k-i9-9900k-rtx-2060-2070-2080.html).
Has anyone else encountered this issue with this chassis, using this driver?

**Comment by pal1000** [comment]
I got no such reports. Maybe you have to disable the speakers via Realtek Audio Console or Windows,

**Comment by Brainiarc7** [comment]
Hmm, installing the generic driver from Realtek fixed the issue for me, somehow.
