### ISSUE TITLE
Please add an option to remove auto enter Safe Mode and CMD runonce

### ISSUE THREAD

**Issue by NinjaUmbra** [pal1000/Realtek-UAD-generic#119]
Most of the time, we can enter the system, please add an option before confirm install UAD-generic.
In my case, I don't want to force copy the latest sys file, so I have to close the bat after your bat will replace the new version with the common one.
Please also add an option not to replace the newer version.
Thx for all

**Comment by NinjaUmbra** [comment]
The truth is: In my windows 11, i cannot return to normal mode even my pc has no blue screen.
Each time I enter the desktop, the bat cmd windows will always come to me unless I delete the reg key

**Comment by NinjaUmbra** [comment]
already know how to disable safe mode and bat auto 
just delete related folder
But can you add the option so that not nedd delete ervery new pack

**Comment by pal1000** [comment]
I don't know why a very small number of users have problems with Windows shell manipulation based auto-start logic.  It appears to be robust for everyone, but something fails for some users for some reason.   UAC being disabled might be the cause of failure.

**Comment by NinjaUmbra** [comment]
I can provide my environment for you to fix this if you wish to do that
