### ISSUE TITLE
Latest Release 6.0.9481.1 doesnt install properly

### ISSUE THREAD

**Issue by DymondZ** [pal1000/Realtek-UAD-generic#134]
First of all thank you for your efforts!
I have a MSI B450 Gaming Plus motherboard and MSI stopped providing updates to the audio driver on 04/2022 so your Package is very convenient. 
I have been using this a few months now and never had a problem updating the driver before.

Everytime I update the driver I check in the Realtek UWP application the version number. Because it has been accurate before not as Device Manager which always showed 6.0.9275.1. But this is somewhat explained in your README.

Now on the latest release the Realtek application shows 6.0.9275.1
I tried rebooting and also executing the installer a second time and had no luck. Am I missing something?
Also I noticed the filename of the release misses a figure (6.0.948.1). Don't know if that relates to each other.

Here an Image of the Realtek Audio Console
![image](https://user-images.githubusercontent.com/61392964/223564066-b992e310-b2fc-4295-8b33-b4f7f4ee8a8e.png)

If you need more information I would be happy to provide them to you.

Greetings and thanls again for your work

EDIT: Theres no Audio Device connected to the Realtek Device, hence the App seems blank. Thats not an issue.

**Comment by epman100** [comment]
> First of all thank you for your efforts! I have a MSI B450 Gaming Plus motherboard and MSI stopped providing updates to the audio driver on 04/2022 so your Package is very convenient. I have been using this a few months now and never had a problem updating the driver before.
> 

MSI "appeared" to stop providing driver updates for your [MSI B450 Gaming Plus board](https://www.msi.com/Motherboard/B450-GAMING-PLUS/support#driver) until Monday **March 20, 2023**, when a **6.0.9492.1** driver version showed up.

so remove the unofficial 9481, 9275 or whatever driver version, reboot and download & install the official 6.0.9492.1 driver from the MSI web site instead.

**Comment by DymondZ** [comment]
I'm already on the new driver by MSI but thank you anyways for the information. Should have closed it earlier, sorry for that.
