### ISSUE TITLE
Driver version stuck at 6.0.9275.1

### ISSUE THREAD

**Issue by RKI91** [pal1000/Realtek-UAD-generic#141]
I have installed the latest driver version 6.0.9492.1 but regardless of this in my device manager still show the 6.0.9275.1 version. This has been happen for several updates now. Please help.

**Comment by pal1000** [comment]
See [previous invalid issue reports](https://github.com/pal1000/Realtek-UAD-generic/issues?q=label%3Ainvalid+is%3Aclosed).
