### ISSUE TITLE
Latest driver release flagged as Trojan

### ISSUE THREAD

**Issue by Petarkco** [pal1000/Realtek-UAD-generic#156]
After downloading Unofficial-Realtek-UAD-generic-6.0.9576.1.7z Microsoft Defender removed the zip stating it was a threat. It appears to think it is a trojan. I haven't seen this happen with previous releases.
![image](https://github.com/pal1000/Realtek-UAD-generic/assets/25685344/e4debb22-f518-48d6-9355-80c847a9f48c)

VirusTotal scan: https://www.virustotal.com/gui/file/24850f5355444bb0dad268cf52fe442721d41f23240107fc750109a3ae74027d/detection

**Comment by pal1000** [comment]
I saw some AVs throw false positives at ultra compressed 7-zip archives. Sophos is most accurate. It detects NirCMD as PUA,, but it has legitimate use here.
