### ISSUE TITLE
Which packages support hardware ID DEV_0897 / the ALC897 codec?

### ISSUE THREAD

**Issue by doggogit** [pal1000/Realtek-UAD-generic#160]
I'm currently struggling on where to get a consistent source to download audio drivers from.

Allegedly, the latest R2.83 driver is just a "repackage" of some old Realtek driver that *doesn't* support DEV_0897/ALC897, according to a TenForums reply I saw in their `Latest Realtek HD Audio Driver` post.

And I was just wondering if this GitHub repository is a good source for drivers.

Currently using a AORUS B450 ELITE V2 (rev 1.x) board.

I'm sorry, but I'm really new to this, any help would be appreciated.

**Comment by epman100** [comment]
sorry, doggogit.  **none** of the unofficial UAD generic drivers does not fully support ALC897.

Please go to the www.aorus.com site and download the latest available driver for your Aorus B450 Elite V2 board
