### ISSUE TITLE
Always stuck in the checkservice block

### ISSUE THREAD

**Issue by julianxhokaxhiu** [pal1000/Realtek-UAD-generic#17]
HI,

I did try to use the custom setup.cmd, especially now that there is no more the official setup available, and I noticed that doesn't matter how many users I have ( 1 or more ) it always gets stuck in here:
https://github.com/pal1000/Realtek-UAD-generic/blob/master/setup.cmd#L43

What happens is that I double click, I say yes to give admin permissions, it asks me to log out. Then I re-login and the window starts again with admin permissions. I say yes and it asks again to logout.

This until I remove the startup entry manually.

Any idea what it could be?

Thank you in advance.

**Comment by pal1000** [comment]
That's odd, I didn't experience this in my tests.  Did this line executed:
https://github.com/pal1000/Realtek-UAD-generic/blob/master/setup.cmd#L35

**Comment by julianxhokaxhiu** [comment]
I think it didn't because this line returns an error ( https://github.com/pal1000/Realtek-UAD-generic/blob/master/setup.cmd#L33 ) as I do not have a key within that path, although my realtek driver is fully installed and working properly ( I've installed your latest release that included the official setup ).

I've instead found that I have a similar key under this path:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run
```
Could it be that the official setup creates an entry elsewhere?

**Comment by pal1000** [comment]
Thanks for finding that key with `RtkAudUService` value, I also have it along the usual one when the driver is installed and running.  I need to prepare 6.0.8835.1 which will give me the opportunity to test what happens in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run` when `RtkAudUService` value is removed from `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

**Comment by julianxhokaxhiu** [comment]
Ping me back again when it's ready to be tested. I'll be happy to try it out :) Thank you

**Comment by pal1000** [comment]
6.0.8835.1 is out. Good luck.

**Comment by julianxhokaxhiu** [comment]
Fixed by the PR successfully! Thank you also for your attempt :)
