### ISSUE TITLE
Question: There is a OEM DCH type Realtek driver for my audio chip from the same manufacturer as my motherboard. Should I use Generic driver or OEM?

### ISSUE THREAD

**Issue by Comeonnoob** [pal1000/Realtek-UAD-generic#175]
![изображение](https://github.com/user-attachments/assets/915f09c2-3933-4486-af43-569901bd309f)
Driver: https://download.asrock.com/Drivers/All/Audio/Realtek_Audio(v9679.1_UAD_WHQL_RTK).zip

**Comment by pal1000** [comment]
OEM is recommended.

**Comment by Comeonnoob** [comment]
Oh, then I am staying on OEM drivers

**Comment by epman100** [comment]
> Oh, then I am staying on OEM drivers

indeed, use OEM based driver but here's the newest one - version [6.0.9703.1](https://download.asrock.com/Drivers/All/Audio/Realtek_Audio(v9703.1_UAD_WHQL).zip).  use that one instead of the 6.0.9679.1 version
