### ISSUE TITLE
Experiencing Audio Compression 

### ISSUE THREAD

**Issue by updatesvc** [pal1000/Realtek-UAD-generic#19]
Hi,
Hopefully, this is a good place to post this, if not I will happily close the issue.
I have a hp laptop pavilion 15
## **Specs**
**HP Pavilion 15 Notebook - 15-ay076nia
Device ID : Device HDAUDIO\FUNC_01&VEN_10EC&DEV_0282&SUBSYS_103C81EC&REV_1000
Windows 10 v1903 Enterprise**

I am getting audio compression when using any audio driver:

- Microsoft High Def Audio drivers
- Default Realtek drivers from HP
- Realtek AUD drivers

Is there a way to debug and find out what is causing the compression. Like a hidden APO Limiter or something.. also worth mentioning the default drivers come with DTS

**Comment by pal1000** [comment]
You should post about your problem on forums like [MyDigitalLife](https://forums.mydigitallife.net/threads/update-realtek-high-definition-audio.72236/) or [Station-Drivers](https://station-drivers.com/index.php?option=com_kunena&view=topic&catid=18&id=17&Itemid=858&lang=en)

**Comment by updatesvc** [comment]
thank :)
