### ISSUE TITLE
Can't fetch Realtek Audio Console after installing 6.0.8721.1

### ISSUE THREAD

**Issue by julianxhokaxhiu** [pal1000/Realtek-UAD-generic#2]
Hi,

I did try to install the latest package release and followed the step described by you, but once searching for updates Realtek Audio Console is not updating nor downloading.

Any idea what am I missing? Driver was installed successfully and I'm on Windows 1903 build.

Thank you in advance,
Julian

**Comment by pal1000** [comment]
Let's see if installation was really successful.
1. Open regedit and go to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager` using search field from top and look for a value named `PendingFileRenameOperations`. If it does exist it would be in `Name` column in the table from the right panel. Also if it does exist you have to reboot especially if it contains a data pointing to a location in `windows\system32` before trying again to update Realtek Audio Console. If that value doesn't exist continue with next step. 
- Download [Driver Store Explorer - RAPR](https://github.com/lostindark/DriverStoreExplorer/releases) then post a screenshot of it or multiple screenshots if window has scroll bars, I want to see what 3rd party drivers you have installed. If you want to know what to expect from RAPR, here is the output from my PC:
![rapr-screenshot](https://user-images.githubusercontent.com/1138235/58937873-513a9900-877c-11e9-940f-580087897804.png)

**Comment by julianxhokaxhiu** [comment]
Hi,

I finally managed to get some time to answer this. Here you can find the screenshots required:

![image](https://user-images.githubusercontent.com/1237070/59153135-08703200-8a53-11e9-80dd-82f4cf5d0845.png)
![image](https://user-images.githubusercontent.com/1237070/59153143-132ac700-8a53-11e9-9f0e-8198ca9ad1be.png)

Related to point 1, this is the current value:
![image](https://user-images.githubusercontent.com/1237070/59153153-3786a380-8a53-11e9-81c7-b2c0738aa199.png)

The console still does not appear automatically on Windows Store.

Best regards,
Julian

**Comment by pal1000** [comment]
Found your problem. You have both `HP Audio Hardware support application` and `Realtek Hardware support application` in the driver store at the same time and `HP Audio Hardware support application` is the component that is actually running.  Apparently you installed an OEM specific UAD driver (6.0.1.8569) at some point its remnants are preventing the installation of `Realtek Hardware support application` which is the component that fetches `Realtek Audio Console` from Windows store.
### Steps to correct the problem:
- Open Device Manager and under software components locate `HP Audio Hardware support application`, then disable it, delete it and upon deletion make sure the driver software is also deleted. We want it completely nuked from the driver store;
- from driver store explorer delete `hdx_hpext_hsa.inf` and `hdx_hpext_sr_cnxt.inf` from extensions section;
- Right click computer name in Device Manager and perform a scan for hardware changes.

This should sort your problem.

**Comment by julianxhokaxhiu** [comment]
Thank you very much. The issue is I didn't install any OEM software, but when you install WIndows 10 from scratch, I think it detects the Computer model and installs automatically that driver version.

Would be nice if your setup.bat process could detect this and delete it, to make it transparent to the end user. Even for me which I'm kind of seasoned into the IT :)

Thanks for the help, I'll try your steps and I'll let you know.

**Comment by julianxhokaxhiu** [comment]
Allright, did the steps and as soon as the driver was found again by windows, the Realtek Audio Console installation was done automatically :)

Thank you very much!

**Comment by pal1000** [comment]
It looks like Windows Update installs an OEM UAD driver on your system. Realtek official UAD setup tool is even worse, it only removes core and extension components. There are too many variants of UAD OEM components to implement comprehensive removal for all of them so unfortunately I can't do more,
