### ISSUE TITLE
2 was unexpected at this time

### ISSUE THREAD

**Issue by lllopo** [pal1000/Realtek-UAD-generic#21]
I get "2 was unexpected at this time" with the last 2 versions of the updater. Running windows 10 1909.

**Comment by pal1000** [comment]
Please re-download 6.0.8838.1 and try again.  I am confident I solved the regression.

**Comment by lllopo** [comment]
Yup, you did. It worked fine this time. One small remark : the setup initially restarted my machine, which is OK, but it did it without any warning. A "press any key to restart ..." at that stage would be nice.

**Comment by pal1000** [comment]
Usually it doesn't reboot. You probably clicked through UAC too fast or something was using the sound card like microphone or headsets. Those accessories keep sound card active all the time. I am relying on 3rd-party tools to uninstall, mainly devcon and pnputil so what I can do about it is very limited. Contribution is welcomed though.

**Comment by lllopo** [comment]
Clear.Will have it in mind. Thanks again for the quick reaction.
