### ISSUE TITLE
Installation affects Corsair iCue software.

### ISSUE THREAD

**Issue by DooGie666** [pal1000/Realtek-UAD-generic#24]
When installing your Realtek Drivers after the restart to allow the files to be overwritten the Corsair iCue console does not restart correctly, ie my Keyboard and USB Headset aren't shown up in the iCue Console and the lighting on the Keyboard doesn't show at my settings.
This isn't a complaint but as a heads up for you in case anyone else reports it. 
The workaround is after the Realtek driver is installed fully  the user needs to sign out of Windows then sign back in and the Corsair iCue software then starts correctly.

Keep up the good work, thanks.

**Comment by pal1000** [comment]
Try 6.0,8853.1.

**Comment by DooGie666** [comment]
Thanks pal1000, the Corsair problem goes away with build 8853.1.
