### ISSUE TITLE
Crash when starting as administrator (double click)

### ISSUE THREAD

**Issue by HumbertoFreitas** [pal1000/Realtek-UAD-generic#28]
Firstly thank you very much for the project.

I came to report a problem running setup, setup always crashes when trying to run as administrator (double click) because of the vbscript embedded in it. As my language has accents, they do not transport correctly to the command line.

I found a simple solution that definitely solves the problem in future releases, which is to separate the vbs script from the batch. It would only be necessary for the setup to be started by vbscript, this would solve the problem and and lessens the check the script has to make to know whether running as an administrator or not.

```
WScript.CreateObject("Shell.Application").ShellExecute "Cmd.exe", "/C """ & _
	Left(WScript.ScriptFullName, InStrRev(WScript.ScriptFullName, "\")) & _
	"setup.cmd""", "", "runas", 1
```

**Comment by pal1000** [comment]
@purifiedh2o provided an update to the elevation routine in #18.
Maybe you 2 can collaborate and send a pull request.

**Comment by pal1000** [comment]
6.0.8873.1 has a beta setup that elevates via powershell.

**Comment by HumbertoFreitas** [comment]
> 
> 
> 6.0.8873.1 has a beta setup that elevates via powershell. Please test and report back.

The script fails to start (double click) if the path or folder contains spaces.

Solution:

`powershell -Command Start-Process "'%0'" -Verb runAs 2>nul`

**Comment by pal1000** [comment]
`""%0""` seams to be even better because we can have `'` in filenames.

**Comment by HumbertoFreitas** [comment]
> 
> 
> `""%0""` seams to be even better because we can have `'` in filenames.

True, I forgot this detail.

**Comment by pal1000** [comment]
I updated the beta setup and republished the release package.

**Comment by HumbertoFreitas** [comment]
It is working perfectly.

**Comment by DooGie666** [comment]
Also working here perfectly.

**Comment by akks1981** [comment]
for me too!

**Comment by pal1000** [comment]
I await more feedback regarding beta setup in #29.
