### ISSUE TITLE
Improve support for recovery in safe mode

### ISSUE THREAD

**Issue by pal1000** [pal1000/Realtek-UAD-generic#32]
@HumbertoFreitas, you suggested [this](https://github.com/pal1000/Realtek-UAD-generic/issues/30#issuecomment-574802504), but I have some problems with it, It doesn't work with `HKLM` on my system, but it does with `HKCU`, Using `HKCU` isn't easy though as I have to create the startup entry before elevation and the elevation may happen out of the box if run as administrator is used or user account control is disabled.

**Comment by HumbertoFreitas** [comment]
Could you post the code that you used in the test that "failed"?

**Comment by pal1000** [comment]
I found [this document](https://support.microsoft.com/en-us/help/2021405/standard-user-runonce-and-runonceex-are-not-being-executed) that explains why it didn't work for me. Now I am trying [first answer of this question](https://superuser.com/questions/154686/autostart-program-in-safe-mode) which describes the piggybacking on `explorer.exe` method.

**Comment by HumbertoFreitas** [comment]
> ...I have to create the startup entry before elevation...

You just put the commands that should not have administrator privileges in a separate batch file and execute the code below. It will start the file without elevation (even if the source script is elevated).

Note: It does not accept command line.

`Start "" Explorer.exe "PATH_CMD\file.cmd"`

**Comment by pal1000** [comment]
Please test 6.0.8883.1-2. It has initial safe mode autostart support via Winlogon shell value. Your solution using `RunOnce` has the problem of relying on the assumption that same user as before reboot jogs in after as well. If that's not the case setup won't autostart. Suggestions are welcome regarding the regressions mentioned in release notes.

**Comment by HumbertoFreitas** [comment]
>  If that's not the case setup won't autostart. Suggestions are welcome regarding the regressions mentioned in release notes.

It opened in safe mode, but only the prompt, not the file. I believe that using the runonce solution should not cause any problems if you leave a warning on the screen for the user to log in with the same account.

**Comment by pal1000** [comment]
> It opened in safe mode, but only the prompt, not the file. I believe that using the runonce solution should not cause any problems if you leave a warning on the screen for the user to log in with the same account.

Apparently it has nothing to do with that, instead it's because `net file` command that is used to check for admin rights asks for user action while in safe mode and that's why it stalls immediately. That change happened with elevation switch to powershell. I'll revert the admin rights check, but the elevation with powershell stays untouched as it's far better than anything I had.

**Comment by HumbertoFreitas** [comment]
> Apparently it has nothing to do with that, instead it's because `net file` command that is used to check for admin rights asks for user action while in safe mode and that's why it stalls immediately. That change happened in #18 . I'll revert the admin rights check, but the elevation with powershell stays untouched as it's far better than anything I had.

```
If /i Not "%SafeBoot_Option%"=="" (Goto :Elevated)

Reg Add "HKLM" /F>nul 2>&1
If Not "%ErrorLevel%"=="0" (
Powershell -Command Start-Process ""%0"" -Verb runAs 2
Exit)

:Elevated

Echo Hello World
```


`Reg Add "HKLM" /F` it is the universal way to check if the user has administrator privileges. Works on all versions of Windows.

**Comment by pal1000** [comment]
I re-implemented elevation like this
````
@echo off
@cd /d "%~dp0"
@"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system" >nul 2>&1
@if NOT '%errorlevel%' == '0' (
@powershell -Command Start-Process ""%0"" -Verb runAs 2>nul
@exit
)
````

**Comment by HumbertoFreitas** [comment]
> 
> 
> I re-implemented elevation like this in [4cda436](https://github.com/pal1000/Realtek-UAD-generic/commit/4cda4361ada7be620313271d7bacb80f41afe213):
> 
> ```
> @echo off
> @cd /d "%~dp0"
> @"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system" >nul 2>&1
> @if NOT '%errorlevel%' == '0' (
> @powershell -Command Start-Process ""%0"" -Verb runAs 2>nul
> @exit
> )
> ```

It's working

**Comment by pal1000** [comment]
6.0.8885.1 is out:

This release includes safe mode compatible autostart support as a hidden beta feature. It is activated by creating an empty `beta.ini` file on same folder as `setup.cmd`.
### Known issue
- setup re-runs from the beginning if system reboots when sound card gets enabled in force updater due to lack of safe mode awareness.
### Beta only issue
- 3rd-party Windows shells are replaced with default Windows Explorer.

On another note I wonder if `If /i Not "%SafeBoot_Option%"==""` returns true in safe mode and false otherwise.

**Comment by HumbertoFreitas** [comment]
This variable returns the type of the safe mode (Minimal, network...).

In the case the way it was written in the previous post, it would only trigger the elevation if it was not in safe mode.

Note: In safe mode the prompt always starts as an administrator.

**Comment by HumbertoFreitas** [comment]
It would be interesting for the script to make a backup of the key ("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon | Shell") instead of just writing "explorer.exe"

To prevent problems if this key has a different value.

**Comment by pal1000** [comment]
> This variable returns the type of the safe mode (Minimal, Network...). and when the system is not in this mode, it does not return any value.

Yay, that's exactly what I need for safe mode awareness.
> In the case the way it was written in the previous post, it would only trigger the elevation if it was not in safe mode.
> 
> Note: In safe mode the prompt always starts as an administrator.

I see, whatever. If `@"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system" >nul 2>&1` works correctly, it's fine either way.
> It would be interesting for the script to make a backup of the key ("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon | Shell") instead of just writing "explorer.exe"
> 
> To prevent problems if this key has a different value.
That's all known beta only issue is about. I'll look at `REG IMPORT`, `REG EXPORT`,  `REGEDIT IMPORT` and `REGEDIT EXPORT` and see what's best suited.

**Comment by HumbertoFreitas** [comment]
I will take advantage of the topic and post the answer to this [request](https://github.com/pal1000/Realtek-UAD-generic/projects/2). This key includes both the download and installation of drivers already downloaded.

Key: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching`
Value: `SearchOrderConfig`

`0` = `Disable automatic driver installation`
`1` = `Enable automatic driver installation`

**Comment by pal1000** [comment]
> I will take advantage of the topic and post the answer to this [request](https://github.com/pal1000/Realtek-UAD-generic/projects/2). This key includes both the download and installation of drivers already downloaded.
> 
> Key: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching`
> Value: `SearchOrderConfig`
> 
> `0` = `Disable automatic driver installation`
> `1` = `Enable automatic driver installation`

I read in many forums that pretty much all attempts at stopping only driver installation from Windows update is not something that lasts long.

Back on topic, I managed to solve autostart management issue about resetting Windows shell to Windows explorer in b35fdecb7cb0122eccc2d467aa7016603f02c8ec.

**Comment by HumbertoFreitas** [comment]
You can use this vbs script to get only the value of Shell.

Note: `On Error Resume Next` and `On Error Goto 0` there are no crashes in the script if the key is empty.

**VBScript**
```
On Error Resume Next
	WScript.Echo WScript.CreateObject("WScript.Shell").RegRead("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Shell")
On Error Goto 0
```

**CMD**
```
@For /f "tokens=*" %%a in ('CScript //nologo "VBScript.vbs" %1') do @Echo %%a>Text.txt
```

**Comment by pal1000** [comment]
I took your code and integrated it but for your information there is little benefit from this change. For starters I still need to backup original shell init command to a file, as it's overwritten a few times and there are plenty of hot code spots where Windows can reboot or even crash.

**Comment by pal1000** [comment]
Applied change. Thanks. With this safe mode compatible autostart is done.

**Comment by pal1000** [comment]
6.0.8885.1-2 contains full support for recovery in safe mode. It also includes these fixes:
- fixed setup restarting from scratch if system reboots normally when sound card gets enabled in force updater;
- fixed 3rd-party Windows shells being replaced with default Windows Explorer.
