### ISSUE TITLE
BSOD for me with version 6.0.8886.1

### ISSUE THREAD

**Issue by akks1981** [pal1000/Realtek-UAD-generic#33]
BSOD for me with version 6.0.8886.1! 

Windows 10 Pro 18363.628
ASUS Z97-PRO GAMER

all till ver 6.0.8885.1-2 works 100%

The Problem is the updated "RTKVHD64.sys" from 6.0.8886.1
...
ok i found out that is a bug from the realtek driver 6.0.8886.1!!!!
i updated ur installer with 8888_UAD_Nahimic_2020_0131_213153 from realtek ftp 

and it works 100%!!!!

can be closed! 

sry for my bad english

**Comment by pal1000** [comment]
Just posted 6.0.8888.1. Yes, to downgrade you just need to replace stuff in `Win64`.  Files in `Win64\Realtek` must pass WHQL validation with the exception of `Win64\Realtek\UpdatedCodec` where content for the force updater is present.

**Comment by epman100** [comment]
what Realtek audio chip was akks1981 using when the 8886 driver crashed with a BSOD?

I did get a chance to test the 8886 UAD driver on several different Realtek audio devices a few days ago and 8886 seems to crash into a BSOD with ALC8xx & ALC1xxx series during force update driver install (aka. ALC887, ALC888, ALC892, ALC1150, ALC1200/1220)

The only machine where 6.0.8886.1 of the RTKVHD64.sys file did **not** crash on was a laptop using  Realtek ALC269.  so it seems 8886 works okay on ALC2xx series.

**Comment by akks1981** [comment]
i think it is Realtek ALC 1150

**Comment by akks1981** [comment]
> 
> 
> what Realtek audio chip was akks1981 using when the 8886 driver crashed with a BSOD?
> 
> I did get a chance to test the 8886 UAD driver on several different Realtek audio devices a few days ago and 8886 seems to crash into a BSOD with ALC8xx & ALC1xxx series during force update driver install (aka. ALC887, ALC888, ALC892, ALC1150, ALC1200/1220)
> 
> The only machine where 6.0.8886.1 of the RTKVHD64.sys file did **not** crash on was a laptop using Realtek ALC269. so it seems 8886 works okay on ALC2xx series.

Realtek ALC1150
