### ISSUE TITLE
setups fails with a loop

### ISSUE THREAD

**Issue by pwn0r** [pal1000/Realtek-UAD-generic#34]
I did not find exact info why it may happen in any current issues.

the error I see is as follows:

> Removing Realtek UAD component hdx_genericext_rtk.inf instance #26...
> Microsoft PnP Utility
> 
> Failed to delete driver package: One or more devices are presently installed using the specified INF.
> 
> Removing Realtek UAD component hdx_genericext_rtk.inf instance #27...
> Microsoft PnP Utility
> 
> Failed to delete driver package: One or more devices are presently installed using the specified INF.

This goes in a loop, i.e. non-stop. I had your releases installed in the past, this is the first time this problem appears, just downloaded the most current release i.e. 6.0.8892.1

**Comment by pal1000** [comment]
I think a restart may help, but there is no guarantee. Make sure you disconnect from Internet beforehand otherwise more complications may arise. If that doesn't fix it then you probably have an OEM specific UAD codec INF that is a leftover.  If that's the case follow [this guide](https://github.com/pal1000/Realtek-UAD-generic/blob/master/README.md#switching-from-other-realtek-hd-audio-drivers).

**Comment by pwn0r** [comment]
just a report on that: 

I was able to fix the problem eventually. However worth noting that even with driver explorer this hdx_genericext_rtk.inf could not be deleted (force deleted as well). Even with the audio service stopped and main realtek driver removed by driver explorer.

The reason was these software components of realtek. Like Audio Effects etc. Thing is these were not shown by driver explorer for whatever reason. The solution was to uninstall them from the normal device manager manually one by one. After that this inf file was no longer blocked in driver explorer and could be removed.

**Comment by pal1000** [comment]
I'll have to implement removal of software components via device console. I never thought this would be necessary, but apparently it is in some extreme cases.

**Comment by pal1000** [comment]
Removal of software components via device console is available since 6.0.8911.1.

**Comment by MaxLebled** [comment]
I had this setup issue as well, but I was forced to use "force deletion" of realtekapo.inf in "Driver Store" in order to fix the loop. (Other issues around here pointed me towards this solution.) Now everything's working great!
