### ISSUE TITLE
Unofficial-Realtek-UAD-generic-6.0.8895.1 Partial WHQL notice

### ISSUE THREAD

**Issue by akks1981** [pal1000/Realtek-UAD-generic#35]
...To workaround this setup installs latest WHQL compliant codec component (version 6.0.8856.1) with hardware support application, audio effects and service components taken from latest version and...

...should be "version 6.0.8858.1" and not "6.0.8856.1"  by now  ;-) 

please edit it in the"Partial WHQL notice" text

greetings

**Comment by pal1000** [comment]
Thanks, I'll fix the release notes. I actually included 6.0.8858.1 WHQL codec since 6.0.8889.1.

**Comment by pal1000** [comment]
Thanks, I fixed the release notes. I actually included 6.0.8858.1 WHQL codec since 6.0.8889.1 release.
