### ISSUE TITLE
Sound enhancer not work after replace this driver

### ISSUE THREAD

**Issue by eebssk1** [pal1000/Realtek-UAD-generic#37]
Sound enhancer won't work after replace this driver with realtek driver wizard.Enhancer start normally but no effects.

**Comment by pal1000** [comment]
This driver resets enhancement settings on install. So if you go back to an OEM package you have to redo them.

**Comment by eebssk1** [comment]
> This driver resets enhancement settings on install. So if you go back to an OEM package you have to redo them.

I'm using the drivers made from alanfox2000's github releases.The installation wizard successfully installed the codec and all oem components.However when i tune the enhancer the sound still same but sound lags a bit as usual.

**Comment by eebssk1** [comment]
I have tried reinstall my driver but the enhancer still does nothing.

**Comment by pal1000** [comment]
Try uninstalling my driver (run setup.cmd as usual then answer no when asked to install) before installing an OEM package from @alanfox2000 releases, maybe it is supposed to use a different APO and the one from my package wrongly gets priority.

**Comment by eebssk1** [comment]
> 
> 
> Try uninstalling my driver (run setup.cmd as usual then answer no when asked to install) before installing an OEM package from @alanfox2000 releases, maybe it is supposed to use a different APO and the one from my package wrongly gets priority.

Unfortunately this does not solve the problem either.So i just reinstalled my windows...

  Well feel free to close the issue.

**Comment by pal1000** [comment]
Maybe DDU could have solved it, but it's a nuclear option that may cause other problems.
