### ISSUE TITLE
Keyboard shortcut to disable microphone is broken

### ISSUE THREAD

**Issue by djdelarosa25** [pal1000/Realtek-UAD-generic#39]
Pressing Fn+F4 on my keyboard disables the microphone, as evidenced by a white LED that turns on. It seems like using your drivers breaks this. Would be nice if it could be addressed.

I'm on 6.08911.1-5.

**Comment by pal1000** [comment]
That looks like an OEM specific feature. It's expected to break when using a generic driver. Sorry there is nothing I can do about it.

**Comment by djdelarosa25** [comment]
> That looks like an OEM specific feature. It's expected to break when using a generic driver. Sorry there is nothing I can do about it.

That's alright. Thanks for this project of yours! :)
