### ISSUE TITLE
devcon.exe is required 

### ISSUE THREAD

**Issue by Go2v** [pal1000/Realtek-UAD-generic#40]
Hi !

I have a problem when I run setup.cmd,

for some reason I don't know the program closes itself because devcon.exe is missing, so the program doesn't install.
 
I have followed the README.

Your help would be welcome,

I'll leave you here what the terminal tells me:

**

> Creating setup autostart entry...
> The operation was successful.
> 
> Begin uninstalling Realtek UAD driver...
> 
> Stopping Windows Audio service to reduce reboot likelihood...
> 
> The Windows Audio service is not launched.
> 
> You will get additional help by entering NET HELPMSG 3521.
> 
> 
> Done.
> 
> Removing Audio Universal Service - RtkAudUService64.exe...
> 
> Error: The process "RtkAudUService64.exe" cannot be found.
> 
> Done.
> 
> Windows Device console - devcon.exe is required.
> 
> Press any key to continue...

**

**Comment by pal1000** [comment]
Something went wrong during extraction. Check both archive contents and extracted folder. If `devcon.exe` is in archive but it's missing from extracted folder then something is wrong at your end that's beyond my control.

**Comment by Go2v** [comment]
Unless I'm mistaken, there's no devcon.exe in the archive.

**Comment by akks1981** [comment]
You are doing something wrong! when I unzip this file there is: devcon.exe, README.md and setup.cmd also the following folders: forceupdater, modules, utility and Win64.

**Comment by Go2v** [comment]
Je ne vois même pas ce fichier dans la liste des fichiers du code Github 

C'est très étrange, on dirait qu'on ne parle pas de la même archive. 
J'ai désactiver l'antivirus, c'est pareil malheureusement

Merci pour votre aide !

**Comment by akks1981** [comment]
https://github.com/pal1000/Realtek-UAD-generic/releases/download/6.0.8918.1/Unofficial-Realtek-UAD-generic-6.0.8918.1.zip

**Comment by Go2v** [comment]
This time the file is there, thank you!

**Comment by pal1000** [comment]
Windows Driver Kit Device console utility and Realtek driver binaries aren't part of this repository source code. They are only available in release package.
