### ISSUE TITLE
Realtek Audio Console does not support this PC

### ISSUE THREAD

**Issue by julianxhokaxhiu** [pal1000/Realtek-UAD-generic#42]
Hi,

today I had to do a fresh install of Windows 10, and if you rememeber we have great successful trials of your package working on my machine.

So once I installed it, and cleaned up OEM drivers via RAPR, and installed your package offline ( no Internet ), I can successfully get all your drivers in place. There is no HP Software component in the driver manage anywhere.

Yet, related to the Realtek Audio Console I had to manually fetch it from Windows Store through this link: https://www.microsoft.com/en-us/p/realtek-audio-control/9p2b8mcsvpln?activetab=pivot:overviewtab

I remember this was fetched automatically once installed you driver, nevertheless I did install it from the Windows Store, but when I open it now I do get only the message I used as title of this issue.

Any hint I can follow? Let me know if any log is required in case.

Thank you in advance,
Julian

**Comment by akks1981** [comment]
try http://www.mediafire.com/file/sgzxvkxgt0txhlh/RtkUWP_1.9.215.0.zip/file and if it works upsate to 19.217 via Windows Store!

**Comment by julianxhokaxhiu** [comment]
I found my own issue, but I'll leave it here for whomever may encounter the same issue.

In RAPR check that ALL your Realtek (audio related) drivers AND Sound Effects drivers (which are related to Realtek but masked under this name) are forcefully deleted.

Once you have nothing but the default Windows Audio device driver, then you're good to install this package.

I still had to install manually the realtek audio console from the Store but this time worked like a charm :)

@akks1981 thank you for the link, but it was not an issue of the app itself but on the fact that the system was not "flagged" UAD because of some old Realtek drivers coming out of my HP OEM.
