### ISSUE TITLE
Add support to disable automatic driver updates through Windows Update on Windows 10

### ISSUE THREAD

**Issue by julianxhokaxhiu** [pal1000/Realtek-UAD-generic#45]
Hi,

although I managed to successfully install and clean all the realtek HP drivers on my PC, from time to time, between one poweroff and the other, I do get HP Realtek drivers installed forcefully by Windows.

It seems you can disable this behavior by enabling a Group Policy in the local computer, see https://www.windowscentral.com/how-disable-automatic-driver-updates-windows-10

Would be cool if you could add an option to do that automatically in the setup, either forcefully or asking a simple question. This would allow you drivers to stick in the machine and never ever get overridden.

Thank you in advance :)

**Comment by pal1000** [comment]
I implemented 2 utilities , one that [enables](https://github.com/pal1000/Realtek-UAD-generic/raw/master/utility/enablewindowsupdatedriversdownload.cmd) and one that [disables](https://github.com/pal1000/Realtek-UAD-generic/raw/master/utility/disablewindowsupdatedriversdownload.cmd) drivers download via Windows update based on info from that article you linked.

I'll look into integrating them into setup.

**Comment by cillbill74** [comment]
Those registry keys have never worked for me, I ended up adding the device ID's to the [https://www.howtogeek.com/263851/how-to-prevent-windows-from-automatically-updating-specific-drivers/](WU exclusion list).

**Comment by julianxhokaxhiu** [comment]
@cillbill74 your solution is actually ideal. The only downside of it, it detecting all the affected devices where the drivers will be applied. If there's a way to smartly query that, it could be added to the setup process trasparently, without any kind of question.

While the other solution, which in my case I applied it via gpedit, works just fine. I have to admit I didn't use the registry keys solution but I hope @pal1000 did its own tests and maybe found out they do work.

**Comment by pal1000** [comment]
@cillbill74 solution converted to registry. Please test on hardware that pushes OEM driver:
[disable-audio-driver-update.zip](https://github.com/pal1000/Realtek-UAD-generic/files/4830493/disable-audio-driver-update.zip)

**Comment by cillbill74** [comment]
It works. Much better than what I was doing, I was adding all of the individual IDs for some reason. 
![Screenshot](https://user-images.githubusercontent.com/45872216/85719089-02450600-b6e7-11ea-89b4-65ad0343b57e.png)

**Comment by julianxhokaxhiu** [comment]
Can confirm that it works here too! Same identical outcome as @cillbill74 but on an HP laptop
