### ISSUE TITLE
Getting "Realtek Audio Console doesn't support this machine" after updating windows to 1903

### ISSUE THREAD

**Issue by Velken** [pal1000/Realtek-UAD-generic#5]
Before updating to 1903 Realtek Audio Console worked fine with these UAD Generic, but now it says it is not supported for this machine. Reverting to before 1903 is a workaround, but certain programs I have only work properly on 1903.
![image](https://user-images.githubusercontent.com/8467292/61404289-896de500-a8ad-11e9-8f81-ecab92d5a6d3.png)

**Comment by pal1000** [comment]
To diagnose it I need screenshot from [DriverStore Explorer](https://github.com/lostindark/DriverStoreExplorer/releases). 
Here is the screenshot from my PC so you can have an idea of what to expect:
![RAPR](https://user-images.githubusercontent.com/1138235/61408129-05851e80-a8e8-11e9-9731-f4ca78d907a0.png)

**Comment by Velken** [comment]
![image](https://user-images.githubusercontent.com/8467292/61420228-ed0d0800-a8d7-11e9-90cc-39a53dfd7a43.png)


![image](https://user-images.githubusercontent.com/8467292/61420242-fb5b2400-a8d7-11e9-9458-b5a9a2716e08.png)


![image](https://user-images.githubusercontent.com/8467292/61420251-031ac880-a8d8-11e9-995c-c210e615018b.png)

**Comment by pal1000** [comment]
It looks like with the upgrade to Windows 10 Version 1903, Windows installed an old Realtek Audio driver behind your back with version 6.0.1.8564 as shown in second part of your screenshot. That driver have to be removed before you can get the generic driver to run and Realtek Audio Console with it.
Try finding this old driver installation record in Programs and Features in Control Panel. If it's there remove it and make sure you cut Internet connection before rebooting as you don't want this issue to reoccur. After reboot there should be nothing left to hinder the generic driver from running and Realtek Audio Console should work again. You can reconnect after the generic UAD driver has started.
If there is no entry in Programs and Features for the old driver you can remove it with DriverStore Explorer.
After removing it with DriverStore Explorer, do a scan for hardware changes in Device Manager that should hopefully let the generic driver and Realtek Audio Console to work.

**Comment by Velken** [comment]
It worked, it was really windows update's fault.
Your generic driver is even better than the one that came with the laptop, now the FN media keys (pause/play, stop, skip back, skip forward) work very well, even with chrome (the console wasn't working with them previously with just the stock drivers).

**Comment by Velken** [comment]
Little update with some info:
Did some tests with other devices, turns out Realtek really has some crappy spaghetti code.
To fix either RPC or Doesn't Support errors, so far this has worked 100% of the time of the 3 machines I tested:
-Download pal1000's driver
-Close any realtek process (audio related or not)
-Remove driver via Device Manager
-ALL Realtek drivers with DriverStore Explorer
-Turn off internet (to prevent windows from installing drivers)
-Reboot and install audio drivers using pal1000's installer (not sure if installing unofficial and minimal Realtek UAD generic package is necessary, but I've found it to not work 100% of the times on one of the machines with older hardware)
-Reboot after install, Audio Console should work now
-Turn on internet and download and install other non-audio Realtek drivers that were removed (i.e. Network Ethernet Controller)

**Comment by Velken** [comment]
Update 2:
Whenever Realtek Audio Console updates automatically, `hdxsst4da.inf` finds its way back into the system, it does not happen with manually going on MS Store and clicking update, guess is something hooked to Windows Update.
Manually removing it with Driver Explorer fixes the issue without need to restart.
Something annoying but can live with.
