### ISSUE TITLE
How to unistall driver?

### ISSUE THREAD

**Issue by Pillownosek** [pal1000/Realtek-UAD-generic#51]
I didn't see the file "restorewindowsnormalstartup" at first time and started deleting all folders associated with Realtek & Realtek Semiconductor Corp. using the program DriverStore.
Folders deleted successfully, but the driver is still installed... where are all the other files and how to and how to delete them? help pls @pal1000

**Comment by pal1000** [comment]
Run setup then answer no when it asks to re-install. That's it.
