### ISSUE TITLE
Getting this error after all " Can not connect to RPC service" 

### ISSUE THREAD

**Issue by madakab** [pal1000/Realtek-UAD-generic#6]
Hello, 
I hope you are having a nice day,
I previously read topic #5 and did the following steps :
1-disconnected internet and uninstalled Realtek from (add and remove programs)
2-rebooted and checked it's clear
3-installed the generic driver you provided it today
4-checked the console and still getting the same error.
here's the SS of my driver
![Screenshot_12](https://user-images.githubusercontent.com/32437721/61479768-cfea3f00-a994-11e9-8b3e-b927c35b19f8.png)
![Screenshot_13](https://user-images.githubusercontent.com/32437721/61479770-cfea3f00-a994-11e9-9ed9-2682390a6da3.png)
I hope you can help me in fixing this because I'm in a critical situation 
with all my love on trying to help around 💯

**Comment by pal1000** [comment]
The only thing that is not part of my generic package is realtekasio, but that should be harmless. Try opening Services as admin and start Realtek Universal Audio Service. I think it didn't start for some reason.

**Comment by madakab** [comment]
> The only thing that is not part of my generic package is Realtek ASIO, but that should be harmless. Try opening Services as admin and start Realtek Universal Audio Service. I think it didn't start for some reason.

Sorry forgot to say that I disable it as a try to fix it out because I read somewhere that someone just disabled it and it worked. 
So the problem isn't from it.

**Comment by pal1000** [comment]
Try manually starting Realtek Universal Audio Service as I suggested.

**Comment by madakab** [comment]
I tried that and the Realtek Universal is working but i have the same probelm 🙁

**Comment by pal1000** [comment]
I don't see any driver conflict on your screenshots, so I don't know what's wrong.
You could try log out then log back in.  If it still doesn't work grab a screenshot from Registry Editor of this key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`.

**Comment by madakab** [comment]
here it is not missing :
![image](https://user-images.githubusercontent.com/32437721/61542748-78a2a800-aa42-11e9-93b1-0d04a35b343b.png)

**Comment by pal1000** [comment]
We hit a dead end.  Maybe your sound card requires a 3rd party component for Realtek Audio Console to function. If that's the case generic driver will never be fully functional.
To get some insight I need your sound card hardware ID from Device Manager. Here is mine as example:
![sound-card-hardware-IDs](https://user-images.githubusercontent.com/1138235/61561697-4318b180-aa78-11e9-91a9-93e66625d5da.png)

**Comment by madakab** [comment]
Here you go Its Solved: 
I did the following :
1-uninstalled the driver from device manager
2- went to driver-store deleted every simple driver from Realtek 
3- deleted Realtek folder.
4- rebooted 
5- installed Your driver.
6- rebooted and it didn't work
7- did same from 1-3 
8- didn't reboot just installed the driver.
9- rebooted and its woked <3 
sorry for the long story but wanted to be clear as much as I can 
Thx for your help I'm glad.

**Comment by pal1000** [comment]
Flushing driver settings solved it. It looks like ASIO was a real problem on your system as disabling and removing it wasn't enough. Glad you got it solved. You should probably update your LAN Ether driver too as you probably removed it as well when you removed all Realtek drivers.
