### ISSUE TITLE
Realtek driver setup problem.

### ISSUE THREAD

**Issue by connnorturner** [pal1000/Realtek-UAD-generic#64]
Hello there, I'm having an issue with the setup.cmd, I know it's something on my end as I had it installed but I must've deleted it somehow.
Whenever I run the setup/cmd, after following previous steps such as deleting old drivers, I get this:
"""
Removing generic Realtek UAD components...

Removing Realtek UAD component realtekservice.inf instance #1...
Microsoft PnP Utility

Failed to delete driver package: One or more devices are presently installed using the specified INF.
"""
and the number increases everytime, leading to an infinite loop. 

Any help would be greatly appreciated.

Cheers,
connnorturner

**Comment by pal1000** [comment]
Grab [Driver store explorer](https://github.com/lostindark/DriverStoreExplorer/releases) then remove `realtekservice.inf` using force delete option. It probably remained tied to a driver that's not installed anymore

**Comment by connnorturner** [comment]
Thanks, 
but i've now encountered a different problem. I can run the setup.cmd nearly the whole way through but after doing the install, I don't have the realtek app.

![image](https://user-images.githubusercontent.com/76792576/103438747-54cf2400-4c2e-11eb-9692-cc64e3071b72.png)
 i get an invalid syntax
"REG ADD /?"


thanks for all the help

**Comment by pal1000** [comment]
Does force updater runs to the end despite that error?

**Comment by connnorturner** [comment]
yeah, but i now can't open the realtek app, it seems to have disappeared? not sure whats happened.

cheers again, 
connnorturner
