### ISSUE TITLE
How to know what driver to download for my system?

### ISSUE THREAD

**Issue by necros2k7** [pal1000/Realtek-UAD-generic#70]
mine is HDAUDIO\FUNC_01&VEN_10EC&DEV_0662&SUBSYS_1565821E&REV_1003

**Comment by pal1000** [comment]
Ask questions like this on forums like this:
- https://station-drivers.com/index.php?option=com_kunena&view=topic&catid=18&id=17&Itemid=858&lang=en
- https://forums.mydigitallife.net/threads/update-realtek-high-definition-audio.72236/
- https://www.tenforums.com/sound-audio/135259-latest-realtek-hd-audio-driver-version-2-a.html
