### ISSUE TITLE
App not working because KERNELBASE.dll

### ISSUE THREAD

**Issue by Osahashi** [pal1000/Realtek-UAD-generic#71]
I thought with a new version/new installation I could fix my problem but no, my Realtek Audio Console doesn't work anymore, and I have no ideas anymore how to fix it...

I get this error here (sorry it's in German):

```
Name der fehlerhaften Anwendung: RtkUWP.exe, Version: 1.25.245.0, Zeitstempel: 0x602e1491
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.906, Zeitstempel: 0x2f2f77bf
Ausnahmecode: 0xc000027b
Fehleroffset: 0x000000000010b2dc
ID des fehlerhaften Prozesses: 0x1db8
Startzeit der fehlerhaften Anwendung: 0x01d734fe92c229e3
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\RealtekSemiconductorCorp.RealtekAudioControl_1.25.245.0_x64__dt26b99r8h8gj\RtkUWP.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: a5c65a16-eafd-47d5-8428-785d79a315d8
Vollständiger Name des fehlerhaften Pakets: RealtekSemiconductorCorp.RealtekAudioControl_1.25.245.0_x64__dt26b99r8h8gj
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App
```

What I tried so far:

- uninstall/remove the Realtek Audio Console app complete
- reinstall the driver
- sfc /scannow (no problems found)
- sfcfix (no problems found)
- DISM

After remove the app completely there is stuff left in WindowsApps, but I can't delete it without the rights, not sure should I do it or not.

**Comment by pal1000** [comment]
Try resetting Realtek Audio console: right click on icon - More - App settings - Reset.

**Comment by Osahashi** [comment]
> 
> 
> Try resetting Realtek Audio console: right click on icon - More - App settings - Reset.

Already did a few times, I reset the app settings in the settings, I remove the app, I reinstall, its only this app that makes trouble, every other app works without problem. The app launches and then disappear immediately.

I also removed and reinstalled all VC++ and Runtime to see if this is maybe the problem but no, it doesn't change anything. My KERNELBASE.dll is version 10.0.19041.906 from 25.03.2021, it seams the newest version, I could only find older versions online.

I'm searching around the internet and try everything, nothing did anything.

**Comment by Osahashi** [comment]
I didn't find a way to fix it, I made an inplace update/repair with an ISO/USB-Stick and the app works again now

**Comment by Osahashi** [comment]
If someone found this through search because he has the same problem, I think it is related to the process "WpnUserService" the app crashed again after disabling this process, it needs WpnUserService running for whatever reason, it was not the case in older Windows version, happens first in 21H1

**Comment by epman100** [comment]
> 
> 
> If someone found this through search because he has the same problem, I think it is related to the process "WpnUserService" the app crashed again after disabling this process, it needs WpnUserService running for whatever reason, it was not the case in older Windows version, happens first in 21H1

why were you using 21H1?  that is not even released to the public yet and still in the beta & release preview channels

**Comment by Osahashi** [comment]
> why were you using 21H1? that is not even released to the public yet and still in the beta & release preview channels

19043.928 is the final version of 21H1 and already released for download - https://blogs.windows.com/windows-insider/2021/04/28/preparing-the-windows-10-may-2021-update-for-release/
I'm currently on 21H1 Build 19043.964
