### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by DealsBeam** [pal1000/Realtek-UAD-generic#73]
Getting this https://prnt.sc/12i1vwg it's just stuck here

I've uninstalled using DriverStoreExplorer, DDU, etc. keep getting stuck on this

Any help?

**Comment by pal1000** [comment]
It looks like it gets stuck [here](https://github.com/pal1000/Realtek-UAD-generic/blob/1b745fd261f464fd73f74d2f83ca9dff463eb7f3/forceupdater/forceupdater.cmd#L42). You can try running without that command. Take it out by changing it to `@rem net stop Audiosrv /y`.

**Comment by DealsBeam** [comment]
Thanks, it ended up working by its self.

Is it possible to make the setup.cmd run in Powershell instead of command line?

**Comment by pal1000** [comment]
> Is it possible to make the setup.cmd run in Powershell instead of command line?

In elevated powershhell run ` cmd /c Realtek-UAD-generic\setup.cmd`.

**Comment by DealsBeam** [comment]
Thank you for the help
