### ISSUE TITLE
Cant access dekstop after clean Driver UAD Realtek

### ISSUE THREAD

**Issue by hideandseekstheorder** [pal1000/Realtek-UAD-generic#75]
idk how to restore my dekstop again

**Comment by hideandseekstheorder** [comment]
black screen but i can login and using task manager

**Comment by hideandseekstheorder** [comment]
when i open ms-settings using cmd or Windows Run using task manager , i got this thing " file system error -2018374635"

**Comment by pal1000** [comment]
Do `File` `-` `Run new task` from Task manager and run `explorer`.
Open an elevated command prompt and run
`REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /t REG_SZ /v Shell /d "explorer.exe" /f`

**Comment by hideandseekstheorder** [comment]
> Do `File` `-` `Run new task` from Task manager and run `explorer`.
> Open an elevated command prompt and run
> `REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /t REG_SZ /v Shell /d "explorer.exe" /f`

Thank you, its working!
