### ISSUE TITLE
Should I unistall the Realtek Audio Console?

### ISSUE THREAD

**Issue by Katzenwerfer** [pal1000/Realtek-UAD-generic#80]
The title describes my issue
I'm not really sure if uninstalling it is a good idea. Mostly because windows sucks ass and sometimes stuff like the audio console don't get reinstalled :p

**Comment by pal1000** [comment]
Realtek Audio Console sole purpose is to configure Realtek UAD settings. If default settings are fine for you, you can manage without it.
