### ISSUE TITLE
Waking up from sleep

### ISSUE THREAD

**Issue by TyroSpy** [pal1000/Realtek-UAD-generic#83]
My system often waking up from sleep
Event Viewer:
`The system has returned from a low power state.

Sleep Time: ‎2021‎-‎07‎-‎26T21:05:18.976584500Z
Wake Time: ‎2021‎-‎07‎-‎26T21:05:25.702933100Z

Wake Source: Device -High Definition Audio Controller`

`SleepTime 2021-07-26T21:05:18.9765845Z 
  WakeTime 2021-07-26T21:05:25.7029331Z 
  SleepDuration 552 
  WakeDuration 1203 
  DriverInitDuration 654 
  BiosInitDuration 2187 
  HiberWriteDuration 0 
  HiberReadDuration 0 
  HiberPagesWritten 0 
  Attributes 1912623360 
  TargetState 4 
  EffectiveState 4 
  WakeSourceType 5 
  WakeSourceTextLength 32 
  WakeSourceText High Definition Audio Controller 
  WakeTimerOwnerLength 0 
  WakeTimerContextLength 0 
  NoMultiStageResumeReason 0 
  WakeTimerOwner  
  WakeTimerContext  
  CheckpointDuration 269`

**High Definition Audio Controller** located in the System Devices and have Microsoft driver v10.0.19041.1081
`PCI\VEN_8086&DEV_A348&SUBSYS_87971043&REV_10
PCI\VEN_8086&DEV_A348&SUBSYS_87971043
PCI\VEN_8086&DEV_A348&CC_040300
PCI\VEN_8086&DEV_A348&CC_0403`

My specification:
Windows 10 Pro
Version: 21H1
OS build: 19043.1110
M/B: ASUS TUF Z390-PRO GAMING
Audio: Realtek ALC S1200A
Realtek-UAD Generic package: 6.0.9205.1

**Comment by pal1000** [comment]
Based on hardware ID, I think it's an Intel audio device that is causing the trouble.  You can try disabling it and see what happens as it looks like it doesn't even use Realtek UAD Generic driver

**Comment by TyroSpy** [comment]
I have "Intel® Display Audio" in the Sound controller with this id:
`HDAUDIO\FUNC_01&VEN_8086&DEV_280B&SUBSYS_80860101&REV_1000
HDAUDIO\FUNC_01&VEN_8086&DEV_280B&SUBSYS_80860101`

And with last Intel driver v10.27.0.10

When I tried to disable "High Definition Audio Controller(Microsoft)" the sound completely disappeared.

**Comment by pal1000** [comment]
It looks like your sound card is Intel SST enabled. Installing Intel SST driver may solve your problem.

**Comment by TyroSpy** [comment]
I tried to download last Intel SST WDM driver but this was be incompatible with my device and cannot be installed.
I asked other users who have integrated Intel UHD graphics and they also have **High Definition Audio Controller(Microsoft)** in the system device but slightly different SUBSYS Id. Perhaps it M/B-specific device from OEM. But if you are sure it has nothing to do with your driver package, then I think that the topic can be closed.

**Comment by pal1000** [comment]
Yes my UAD generic package only supports
- `HDAUDIO\\FUNC_01&VEN_10EC`
- `INTELAUDIO\\FUNC_01&VEN_10EC`
