### ISSUE TITLE
Stuck on removing generic Realtek UAD components

### ISSUE THREAD

**Issue by bluelhf** [pal1000/Realtek-UAD-generic#86]
<img align="right" src="https://user-images.githubusercontent.com/52505120/128691751-8397b2c5-338e-4f97-93c3-4fc985ff2e8e.png" width="50%"/>

When installing, the installer gets stuck on the "Removing generic Realtek UAD components..." stage, going into an infinite loop of seemingly removing hundreds of instances of `hdx_genericext_rtk.inf`...

Running Windows 11 Home 21H2 22000.120 with an existing Realtek (R) Audio (6.0.8882.1) driver that came with a Windows update...

**Comment by pal1000** [comment]
Post driver store explorer screenshots.  There may be a non-generic Realtek UAD INF keeping `hdx_genericext_rtk.inf` in use.

**Comment by bluelhf** [comment]
Fixed after uninstalling the Realtek (R) Audio device (and drivers) in Device Manager. I have a medical condition called "Stupidity", it prevents me from reading the README, manual, or other instruction set provided by a kind developer before using their program.

My bad.
