### ISSUE TITLE
Realtek USB Audio Drivers

### ISSUE THREAD

**Issue by HHH0003** [pal1000/Realtek-UAD-generic#95]
I installed a Sound Blaster audio card, it uses a Realtek ALC1220 chip and your latest driver works perfectly with this sound card.  My computer has the Realtek ALC4050H codec (AMD board) and I have problems with it making popping noise and truncated audio using the built in audio ports... the reason I installed a sound card.  I know the ALC4050H driver is powering down to D2 after 10 seconds causing the popping noise.  It takes 750ms for the driver to go from D2 to D0 causing 750ms of lost sound.   
My question is can this ALC4050H driver (Codec) be modified changing its Power Data Bus and Codec to D0?  
The Realtek HDA driver test utility shows your driver reporting Power Data Bus(D0) Codec(D0)... The tool doesn't report anything from ALC4050H driver.  
The ALC4050H uses the Realtek Audio Control Panel and everything shows up perfectly and totally intergrated.  
If I use the generic Windows USB 2.0 Audio codec, the sound problems will go away as it runs in D0.  The Windows driver doesn't support the Realtek Audio Control Panel.

**Comment by pal1000** [comment]
There is a Realtek USB Audio driver and that doesn't seam to be motherboard/card specific making things way easier, just one driver for every ``USB\AUDIO\VEN_10EC` device.

**Comment by HHH0003** [comment]
I attempted to install a generic Realtek USB Audio Driver... my device ID is much different from "USB\AUDIO\VEN_10EC" and using the driver caused a blue screen.  My front device ID is "USB\VID_17AA&PID_104D&REV_0010&MI_00" the rear is "USB\VID_17AA&PID_1046&MI_00"  It's very frustrating because my computer is new and Lenovo doesn't want to address the issue.  If the Lenovo Realtek driver power data was changed from D2 to D0, the problem would be fixed.

**Comment by pal1000** [comment]
Maybe this helps: https://www.catalog.update.microsoft.com/Search.aspx?q=6.3.9600.*
Sort by date descending.

**Comment by HHH0003** [comment]
I tried several of the Realtek USB audio drivers you mentioned, all must have power saving enabled because they power down after 10 seconds and take 750ms to power back up. Only the Windows generic USB 2.0 Audio driver works correctly audio wise… the Realtek audio control doesn’t recognize the rear port with the Windows driver.

**Comment by pal1000** [comment]
Maybe tweaking power management in RAC helps.
![image](https://user-images.githubusercontent.com/1138235/145809531-2d860734-55a2-4420-b41e-72cb48197318.png)

**Comment by HHH0003** [comment]
That option doesn’t show up on my RAC panel. Perhaps that function needs to be enabled somewhere else inside Windows… I know there’s registry settings which allows “extra” power management settings. Maybe if that option was available to me, it would solve the problem.

**Comment by epman100** [comment]
> There is a Realtek USB Audio driver and that doesn't seam to be motherboard/card specific making things way easier, just one driver for every ``USB\AUDIO\VEN_10EC` device.

sorry pal1000 - Realtek USB audio drivers do **NOT** use ``USB\AUDIO\VEN_10EC" as the hardware ID.
hardware IDs for Realtek USB audio are completely different (they begin with USB\VID_xxxx) than the IDs for Realtek HD audio

**Comment by HHH0003** [comment]
I’ve contacted Lenovo about this issue, not sure what’s going to be done yet… according to the agent probably nothing. I requested a buy back if the solution is nothing.  I’m guessing the advanced power settings aren’t available and show up only when a computer has or is on battery power.  
If the generic Windows USB Audio 2.0 driver works correctly, I’m sure the Realtek driver can be modified to function correctly. The question is wether Lenovo will do this or not.

**Comment by epman100** [comment]
> Maybe latest generic helps `https://www.catalog.update.microsoft.com/Search.aspx?q=6.3.9600.*` Sort by date descending.
> 
> You may also need RealtekUSBAPO from [here](https://www.station-drivers.com/index.php/en/forum/hd-sound/460-drivers-realtek-high-definition-audio-codecs-usb-uad-hda?start=6).
> 
> You can reuse RealtekHSA and RealtekService from my package.

unfortunately there were **never** really "generic" Realtek USB audio drivers from MUC as they don't have the equivalent versions of "generic" INF files (like HDXRT.inf & HDXRTSST.inf for standard Realtek HDA UAD/DCH drivers).

The **RtDUsbAD.inf** file for the Realtek USB audio driver from MUC has device IDs beginning with "USB\VID_0BDA" and OEM based INF files like RtDUsbAD_asus.inf, RtDUsbAD_gigabyte.inf & RtDUsbAD_msi.inf use vastly "unique" VID_xxxx IDs (for Asus it's VID_0B05, for Gigabyte it's VID_0414 and for MSI it's VID_0DB0)

**Comment by HHH0003** [comment]
The latest version from the Microsoft Catalog 6.3.9600.2330 seems to be Dell specific.  The 6.3.9600.2325 is universal for any motherboard using ALC4050H and will install on my computer without issue.  The truncated sound issue is gone as of driver build 6.3.9600.2321 as it delays playback until the chip is at D0 power state.  The popping sound is still there when the chip goes to D2... but is much less noticeable with my NVidia M4000 card.  I can't explain why that makes a difference.  I had to stop using my AMD W5500 as the latest drivers are really buggy causing blue screens and browser lockups.

**Comment by epman100** [comment]
> The latest version from the Microsoft Catalog 6.3.9600.2330 seems to be Dell specific. The 6.3.9600.2325 is universal for any motherboard using ALC4050H and will install on my computer without issue. The truncated sound issue is gone as of driver build 6.3.9600.2321 as it delays playback until the chip is at D0 power state. The popping sound is still there when the chip goes to D2... but is much less noticeable with my NVidia M4000 card. I can't explain why that makes a difference. I had to stop using my AMD W5500 as the latest drivers are really buggy causing blue screens and browser lockups.

while the 6.3.9600.2330 version from MS is Dell specific (not for "All OEMs" or universal), there is a [6.3.9600.232**6** version](https://www.catalog.update.microsoft.com/Search.aspx?q=6.3.9600.2326) available that is sort of universal.

although Lenovo themselves recently seemed to have released a [6.3.9600.2344 version](https://support.lenovo.com/us/en/downloads/ds546659-harman-apo-driver-for-windows-iot-10-64-bit-thinksmart-hub-teams) (labeled as a "Realtek APO driver") specific for Thinkhub Smart Teams, it does have the necessary RtDUsbAD_lenovo.inf and ExtRtXUsb_Lenovo_RTK.inf files as well as updated Realtek USB APO Effects Component & Realtek Audio Universal Service drivers that support IDs "USB\VID_17AA&PID_1046" & "USB\VID_17AA&PID_104D" - download & run that EXE package directly to update all drivers and Realtek software components and reboot

**Comment by HHH0003** [comment]
Different number… same person. The same one that likes to turn off after 10 seconds. 
I was hoping this build would have fixed the popping issue, it didn’t. 
Thanks for letting me know about this new version… it was worth testing.

**Comment by epman100** [comment]
> Different number… same person. The same one that likes to turn off after 10 seconds. I was hoping this build would have fixed the popping issue, it didn’t. Thanks for letting me know about this new version… it was worth testing.

I noticed in all your comments that you did not even mention which version of Windows you were using when you experienced these problems.  Are you using Win10 or Win11?

try testing the drivers in both Win10 and Win11 (either on separate drive partitions or separate SSD drives) to see if they occur on both Windows versions or one of the other and report back.

**Comment by HHH0003** [comment]
I'll give it a try some time in the future, as for now... it's just easier to use the generic Windows USB 2.0 Audio driver as it works perfectly without any popping sounds.  The only thing the Windows generic driver doesn't do is work with the Realtek Audio Control Panel nor show the correct jack color.  But... it's totally quiet with no popping.  The Realtek Audio driver should function the same as the generic Windows driver... but that's why I started this thread.

**Comment by epman100** [comment]
> I'll give it a try some time in the future, as for now... it's just easier to use the generic Windows USB 2.0 Audio driver as it works perfectly without any popping sounds. The only thing the Windows generic driver doesn't do is work with the Realtek Audio Control Panel nor show the correct jack color. But... it's totally quiet with no popping. The Realtek Audio driver should function the same as the generic Windows driver... but that's why I started this thread.

but you **did not answer my question** in my previous post - Are you using **Windows 10** or **Windows 11**?  type **winver.exe** from the Run dialog box to display the windows version & edition if you don't know what Windows version you have

although this is now pointless, a [6.3.9600.2344 usb audio driver version](https://www.catalog.update.microsoft.com/Search.aspx?q=6.3.9600.2344) showed up on the MS Update catalog site in late November, several days before the Thanksgiving holiday

**Comment by HHH0003** [comment]
I didn't say which version of Windows I was using as the problem exists on both Windows 10 and 11.  But since you did ask, I'm using Windows 11 22H2 (OS Build 22623.891) right now.  The Realtek driver has a mind of its own and will go into sleep D2 mode after 10 seconds of idle sound regardless of what the computer is doing making the annoying popping sound.  This might be okay with a device using an unpowered speaker and probably wouldn't cause a popping sound.  The Windows generic driver supports D2 also... but only when the computer goes into S3 state.

**Comment by HHH0003** [comment]
Last week, Windows update updated my Lenovo P620 BIOS and installed a new Realtek Audio Driver version.  The Realtek driver is a mystery... it's not on Lenovo's website nor Windows update catalog.  The driver version is 6.3.9600.2335 and I can't find it anywhere.  This version is very quiet... I haven't noticed much popping.  The driver also updated the 3 (6 on my computer as it has two Realtek Codecs) Realtek Software components drivers.

**Comment by epman100** [comment]
> Last week, Windows update updated my Lenovo P620 BIOS and installed a new Realtek Audio Driver version. The Realtek driver is a mystery... it's not on Lenovo's website nor Windows update catalog. The driver version is 6.3.9600.2335 and I can't find it anywhere. This version is very quiet... I haven't noticed much popping. The driver also updated the 3 (6 on my computer as it has two Realtek Codecs) Realtek Software components drivers.

the P620 bios/uefi firmware update was not surprising since Lenovo themselves [posted a new version in early January 2023](https://pcsupport.lenovo.com/us/en/products/workstations/thinkstation-p-series-workstations/thinkstation-p620/downloads/driver-list/component?name=BIOS%2FUEFI) (Jan. 5 to be exact).

also it is sometimes normal or typical of Microsoft to issue a driver update only thru windows update and **not** "listed" on the MS update catalog site (although microsoft could offer it on the catalog site a few months later)

**Comment by HHH0003** [comment]
At the time when I first posted this issue, my computer had Windows10.  Shortly afterwards, Windows 11 was released... and I apologize for not saying which version of Window I was using.  There's a lot of frustration when you are dealing with the OEM (Lenovo), and they believe the problem was hardware related vs a driver issue... this is my third replacement computer from them, and I didn't have a computer for almost 3 months January- April of last year... around the time of your first post concerning the issue.  Also, I was working with a sound card as a work around which used a Realtek ALC1220 codec and used pal1000's driver.  I no longer use the sound card. 
Lenovo finally acknowledged there is a driver issue and would inform me when a fix was released... this hasn't happened yet.  Honestly, they probably have forgotten the issue by now.  There's a lot of other users with the same problems with motherboards using the ALC4050H codec.  
Likewise, my replacement computer has an AMD GPU and since Windows 11 22H2 was released, GPU driver compatibility has appeared... flickering video playback and BSOD.  AMD fixed the BSOD issue with a driver update, but the flickering video playback remained until the latest Edge/Chrome update.  It seems that Edge/Chrome broke something with Angle Graphics Backend with AMD GPU's where the workaround was using D3D9 vs the default setting. 
When Windows 10 was first released, there was a few issues with drivers too... it seems they got fixed much quicker vs today.

**Comment by epman100** [comment]
some good news about that 6.3.9600.2335 driver you received sometime in January 2023; eventually Microsoft publicly posted it on the [MS Update Catalog site](https://www.catalog.update.microsoft.com/Search.aspx?q=6.3.9600.2335) this February 2023 (either yesterday Feb. 9 or maybe Feb. 8, depending on which time zone region you reside), although the newest version in the catalog site is [6.3.9600.2349](https://www.catalog.update.microsoft.com/Search.aspx?q=6.3.9600.2349).

as I said before - it's sometimes normal for Microsoft to exclusively release a driver update only thru Windows update and not post it at the same time on their MS Catalog site.  in that case, the 2335 driver did finally become available in the catalog site several weeks later than the windows update only release

so I don't care nor give a damn whether Lenovo themselves releases a new driver for your P620 Lenovo machine, as long as Microsoft provides them for your PC

and don't be surprised when new Win10/Win11 versions (like the upcoming 23H2 version coming in the fall/autumn 2023) are released, that 6.3.9600.2335 audio driver may suddenly or unexpectedly be updated to a much newer version that you may not want down the road.  use tools like wushowhide.diagcab, wumgr or WUMT (windows update minitool) to hide/block unwanted driver updates & don't be caught unaware of that and retain the 2335 driver that is working fine on your machine.

**Comment by HHH0003** [comment]
Although I have stated the 2335 Realtek driver seems to generate less noise vs other versions, it still does generate speaker noise when the power state goes from D0 to D2.  My speakers are quite old, I’m not sure if something newer would be less sensitive to the D0 to D2 power state changes… I’d hate to buy new speakers and still have the popping noise issue.
